/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Error info exposed to JavaScript. */
export interface DetectorErrorInfo {
  code: string
  message: string
}
/**
 * Supported meeting platforms.
 *
 * Matches the TypeScript `MeetingPlatform` type.
 */
export const enum MeetingPlatform {
  MicrosoftTeams = 'MicrosoftTeams',
  Zoom = 'Zoom',
  GoogleMeet = 'GoogleMeet',
  Slack = 'Slack',
  CiscoWebex = 'CiscoWebex',
  Discord = 'Discord',
  FaceTime = 'FaceTime',
  Skype = 'Skype',
  Whereby = 'Whereby',
  GoToMeeting = 'GoToMeeting',
  BlueJeans = 'BlueJeans',
  JitsiMeet = 'JitsiMeet',
  EightByEight = 'EightByEight',
  RingCentral = 'RingCentral',
  BigBlueButton = 'BigBlueButton',
  AmazonChime = 'AmazonChime',
  GoogleHangouts = 'GoogleHangouts',
  AdobeConnect = 'AdobeConnect',
  TeamViewer = 'TeamViewer',
  AnyDesk = 'AnyDesk',
  ClickMeeting = 'ClickMeeting',
  AppearIn = 'AppearIn',
  Unknown = 'Unknown'
}
/** Confidence level for meeting detection. */
export const enum Confidence {
  High = 'High',
  Medium = 'Medium',
  Low = 'Low'
}
/** Verdict from TCC/permission system. */
export const enum Verdict {
  Requested = 'Requested',
  Allowed = 'Allowed',
  Denied = 'Denied',
  None = 'None'
}
/** Raw meeting signal from platform detection. */
export interface MeetingSignal {
  event: string
  timestamp: string
  service: string
  verdict: string
  preflight: boolean
  process: string
  pid: string
  parentPid: string
  processPath: string
  frontApp: string
  windowTitle: string
  sessionId: string
  cameraActive: boolean
  chromeUrl?: string | undefined
}
/** Lifecycle event reason. */
export const enum LifecycleReason {
  Signal = 'Signal',
  Switch = 'Switch',
  Timeout = 'Timeout',
  Stop = 'Stop'
}
/** Meeting lifecycle event (start/change/end). */
export interface MeetingLifecycleEvent {
  event: string
  timestamp: string
  platform: string
  previousPlatform?: string | undefined
  confidence: string
  reason: string
}
/** Detector configuration options. */
export interface DetectorOptions {
  /** Enable debug logging */
  debug?: boolean | undefined
  /** Session deduplication window in milliseconds (default: 60000) */
  sessionDeduplicationMs?: number | undefined
  /** Time without signals before inferring meeting end (default: 30000) */
  meetingEndTimeoutMs?: number | undefined
  /** Emit "Unknown" platform lifecycle events (default: false) */
  emitUnknown?: boolean | undefined
  /** Include sensitive fields like window_title (default: false) */
  includeSensitiveMetadata?: boolean | undefined
  /** Include raw signal in lifecycle events (default: false) */
  includeRawSignalInLifecycle?: boolean | undefined
  /** Probe for active meetings on startup (default: true) */
  startupProbe?: boolean | undefined
}
/**
 * Match a platform from the given context.
 *
 * This is a standalone function for testing matchers.
 */
export declare function matchPlatform(processName: string, windowTitle: string, url?: string | undefined | null, cameraActive?: boolean | undefined | null): string
/** Get the version of the native module. */
export declare function version(): string
/** Get supported platforms as an array. */
export declare function supportedPlatforms(): Array<string>
/** Native meeting detector class exposed to JavaScript. */
export declare class NativeMeetingDetector {
  /** Create a new detector with optional configuration. */
  constructor(options?: DetectorOptions | undefined | null)
  /**
   * Start the detector.
   *
   * On supported platforms, this begins monitoring for meeting activity.
   */
  start(): NapiResult
  /** Stop the detector. */
  stop(): NapiResult
  /** Check if the detector is currently running. */
  isRunning(): boolean
  /** Get the current platform name. */
  platformName(): string
  /** Check if the current platform is supported. */
  isSupported(): boolean
  /**
   * Poll for a new meeting signal from the platform detector.
   * Returns null if no signal is available.
   */
  detect(): MeetingSignal | null
  /** Process a signal (for testing or manual signal injection). */
  processSignal(signal: MeetingSignal): Array<MeetingLifecycleEvent>
  /** Check for meeting end timeout. */
  checkMeetingEnd(): MeetingLifecycleEvent | null
  /** Clean up old sessions. */
  cleanupSessions(): void
}
